const COURSES = [
  {
    id: 1,
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    category: 'Marketing',
    instructor: 'Ava Thompson',
    rating: 4.9,
    studentCount: 12650,
    duration: '6 weeks',
    totalHours: 18,
    price: 129,
    originalPrice: 249,
    icon: '📈',
    categoryColor: 'var(--grad-marketing)',
    thumbnail: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Marketers who want measurable growth', 'Founders needing lead-gen systems'],
      requirements: ['Basic internet & analytics familiarity', 'No prior marketing experience needed'],
      learn: ['Build a complete marketing funnel', 'Run performance ads and optimize ROI', 'Create SEO content plans'],
    },
    curriculum: [
      { title: 'Module 1: Foundations', lessons: ['Marketing basics', 'Funnel thinking', 'KPIs that matter'] },
      { title: 'Module 2: Acquisition', lessons: ['Paid search overview', 'Landing pages', 'Attribution basics'] },
      { title: 'Module 3: Optimization', lessons: ['A/B testing', 'Budget scaling', 'Weekly reporting'] },
    ],
    instructorDetails: {
      name: 'Ava Thompson',
      bio: 'Performance marketer focused on conversion and long-term brand growth.',
      credentials: ['Meta Ads Certified', '10+ years in growth marketing'],
      rating: 4.9,
    },
    reviews: [
      { name: 'Jordan', role: 'Growth Lead', text: 'Very practical and structured. I shipped campaigns within days.' },
      { name: 'Maya', role: 'Freelancer', text: 'The funnel + ROI sections are gold. Clear explanations throughout.' },
      { name: 'Sam', role: 'Startup Founder', text: 'Great pace and real-world examples. Highly recommended.' },
    ],
  },
  {
    id: 2,
    slug: 'project-management',
    title: 'Project Management',
    category: 'Management',
    instructor: 'Noah Williams',
    rating: 4.8,
    studentCount: 9200,
    duration: '5 weeks',
    totalHours: 16,
    price: 149,
    originalPrice: 299,
    icon: '🛠️',
    categoryColor: 'var(--grad-management)',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Team leads', 'Ops managers', 'New project managers'],
      requirements: ['A curious mindset', 'Ability to follow structured templates'],
      learn: ['Plan sprints and milestones', 'Manage scope and stakeholders', 'Track progress with lightweight metrics'],
    },
    curriculum: [
      { title: 'Module 1: Planning', lessons: ['Requirements mapping', 'Milestones & timelines', 'Risk registers'] },
      { title: 'Module 2: Execution', lessons: ['Agile ceremonies', 'Dependencies', 'Communication rhythms'] },
      { title: 'Module 3: Delivery', lessons: ['Reporting dashboards', 'Post-mortems', 'Continuous improvement'] },
    ],
    instructorDetails: {
      name: 'Noah Williams',
      bio: 'Experienced project manager with a focus on measurable delivery and team alignment.',
      credentials: ['PMP-style frameworks', 'Facilitated 20+ cross-functional projects'],
      rating: 4.8,
    },
    reviews: [
      { name: 'Priya', role: 'PM', text: 'Templates are immediately usable. Great for real teams.' },
      { name: 'Ethan', role: 'Product Manager', text: 'Best section on stakeholder communication.' },
      { name: 'Leila', role: 'Operations', text: 'Clear, pragmatic, and well paced.' },
    ],
  },
  {
    id: 3,
    slug: 'video-editing',
    title: 'Video Editing',
    category: 'Design',
    instructor: 'Sophia Martinez',
    rating: 4.7,
    studentCount: 7400,
    duration: '4 weeks',
    totalHours: 14,
    price: 99,
    originalPrice: 199,
    icon: '🎬',
    categoryColor: 'var(--grad-video)',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Creators', 'Marketers', 'Anyone editing for impact'],
      requirements: ['Basic file management', 'Motivation to practice'],
      learn: ['Edit with storytelling structure', 'Color grade for consistency', 'Export optimized formats for platforms'],
    },
    curriculum: [
      { title: 'Module 1: Setup', lessons: ['Editing workflow', 'Cutting rhythm', 'Audio basics'] },
      { title: 'Module 2: Polish', lessons: ['Color correction', 'Titles & motion', 'Sound design'] },
      { title: 'Module 3: Publishing', lessons: ['Export settings', 'Thumbnail strategy', 'Quality checks'] },
    ],
    instructorDetails: {
      name: 'Sophia Martinez',
      bio: 'Editor and motion designer with a focus on clarity, pacing, and brand consistency.',
      credentials: ['Color grading fundamentals', 'YouTube creator experience'],
      rating: 4.7,
    },
    reviews: [
      { name: 'Kim', role: 'YouTuber', text: 'The pacing and audio lessons helped a lot.' },
      { name: 'Omar', role: 'Marketer', text: 'Great templates for titles and export settings.' },
      { name: 'Hannah', role: 'Designer', text: 'Super approachable instruction.' },
    ],
  },
  {
    id: 4,
    slug: '3d-animation',
    title: '3D Animation',
    category: 'Animation',
    instructor: 'Lucas Chen',
    rating: 4.8,
    studentCount: 5100,
    duration: '7 weeks',
    totalHours: 22,
    price: 199,
    originalPrice: 349,
    icon: '✨',
    categoryColor: 'var(--grad-animation)',
    thumbnail: 'https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Motion artists', 'Designers', 'Studios wanting pipelines'],
      requirements: ['General comfort with digital tools', 'Willingness to learn 3D concepts'],
      learn: ['Create character motion', 'Build lighting scenes', 'Animate with industry-ready workflows'],
    },
    curriculum: [
      { title: 'Module 1: Modeling & Basics', lessons: ['Scene setup', 'Materials', 'Camera fundamentals'] },
      { title: 'Module 2: Animation', lessons: ['Keyframes', 'Rigging concepts', 'Timing & spacing'] },
      { title: 'Module 3: Lighting & Render', lessons: ['Lighting setups', 'Render settings', 'Compositing basics'] },
    ],
    instructorDetails: {
      name: 'Lucas Chen',
      bio: '3D artist focused on production-friendly animation pipelines.',
      credentials: ['Motion pipeline experience', 'Portfolio projects in studios'],
      rating: 4.8,
    },
    reviews: [
      { name: 'Zoe', role: 'Animator', text: 'Clear steps and great project structure.' },
      { name: 'Mark', role: 'Studio Lead', text: 'We adapted the workflow for internal training.' },
      { name: 'Elena', role: 'Freelancer', text: 'Strong fundamentals. Loved the lighting module.' },
    ],
  },
  {
    id: 5,
    slug: 'data-analytics',
    title: 'Data Analytics',
    category: 'Data',
    instructor: 'Ethan Brooks',
    rating: 4.9,
    studentCount: 9800,
    duration: '6 weeks',
    totalHours: 20,
    price: 159,
    originalPrice: 329,
    icon: '📊',
    categoryColor: 'var(--grad-data)',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Analysts', 'Product teams', 'Anyone data-curious'],
      requirements: ['Basic spreadsheet skills', 'Comfort reading charts'],
      learn: ['Clean and transform datasets', 'Build dashboards', 'Explain insights to stakeholders'],
    },
    curriculum: [
      { title: 'Module 1: Data Fundamentals', lessons: ['Data types', 'Cleaning', 'EDA'] },
      { title: 'Module 2: Modeling', lessons: ['Metrics', 'Aggregation', 'Feature thinking'] },
      { title: 'Module 3: Communication', lessons: ['Visualization rules', 'Narratives', 'Decision-making'] },
    ],
    instructorDetails: {
      name: 'Ethan Brooks',
      bio: 'Data professional who loves turning messy datasets into clear decisions.',
      credentials: ['BI dashboards', 'Analytics mentoring'],
      rating: 4.9,
    },
    reviews: [
      { name: 'Noor', role: 'Analyst', text: 'Loved the stakeholder communication section.' },
      { name: 'Chris', role: 'PM', text: 'Dashboards became way easier after this.' },
      { name: 'Tara', role: 'Student', text: 'Great examples and practice exercises.' },
    ],
  },
  {
    id: 6,
    slug: 'graphic-design',
    title: 'Graphic Design',
    category: 'Design',
    instructor: 'Mila Novak',
    rating: 4.6,
    studentCount: 6100,
    duration: '4 weeks',
    totalHours: 13,
    price: 89,
    originalPrice: 179,
    icon: '🎨',
    categoryColor: 'var(--grad-design)',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Beginners', 'Creators building portfolios', 'Marketing designers'],
      requirements: ['None — start from basics'],
      learn: ['Design for clarity', 'Typography fundamentals', 'Create brand-ready assets'],
    },
    curriculum: [
      { title: 'Module 1: Foundations', lessons: ['Layout', 'Typography', 'Color systems'] },
      { title: 'Module 2: Production', lessons: ['Brand kits', 'Templates', 'Asset export'] },
      { title: 'Module 3: Portfolio', lessons: ['Case study structure', 'Mockups', 'Feedback'] },
    ],
    instructorDetails: {
      name: 'Mila Novak',
      bio: 'Design mentor focusing on practical layout systems and strong type hierarchy.',
      credentials: ['Brand design systems', 'Teaching experience'],
      rating: 4.6,
    },
    reviews: [
      { name: 'Liam', role: 'Designer', text: 'Solid basics and portfolio guidance.' },
      { name: 'Sarah', role: 'Marketer', text: 'Typography lessons improved our deliverables.' },
      { name: 'Diego', role: 'Creator', text: 'Easy to follow and super helpful.' },
    ],
  },
  {
    id: 7,
    slug: 'web-development',
    title: 'Web Development',
    category: 'Development',
    instructor: 'Olivia Carter',
    rating: 4.9,
    studentCount: 14300,
    duration: '8 weeks',
    totalHours: 26,
    price: 229,
    originalPrice: 399,
    icon: '💻',
    categoryColor: 'var(--grad-webdev)',
    thumbnail: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Developers', 'Engineers transitioning careers', 'Builders'],
      requirements: ['Basic JS familiarity recommended', 'Curiosity and practice'],
      learn: ['Build responsive UI', 'Create RESTful integrations', 'Deploy with confidence'],
    },
    curriculum: [
      { title: 'Module 1: UI & Components', lessons: ['Layouts', 'Reusable components', 'Responsive patterns'] },
      { title: 'Module 2: APIs', lessons: ['Fetch/axios', 'Error handling', 'Auth basics'] },
      { title: 'Module 3: Delivery', lessons: ['Performance', 'Testing mindset', 'Deployment overview'] },
    ],
    instructorDetails: {
      name: 'Olivia Carter',
      bio: 'Full-stack instructor helping students ship real apps with clean patterns.',
      credentials: ['Production deployments', 'Mentoring at scale'],
      rating: 4.9,
    },
    reviews: [
      { name: 'Victor', role: 'Developer', text: 'The API + auth parts are super practical.' },
      { name: 'Grace', role: 'Student', text: 'Really good step-by-step approach.' },
      { name: 'Nina', role: 'Engineer', text: 'Made me confident to deploy.' },
    ],
  },
  {
    id: 8,
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    category: 'Design',
    instructor: 'Charlotte Reed',
    rating: 4.7,
    studentCount: 8400,
    duration: '5 weeks',
    totalHours: 17,
    price: 149,
    originalPrice: 279,
    icon: '🧭',
    categoryColor: 'var(--grad-uiux)',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&auto=format&fit=crop&q=80',
    overview: {
      whoFor: ['Product designers', 'Founders', 'UX enthusiasts'],
      requirements: ['Basic understanding of user flows'],
      learn: ['Design accessible interfaces', 'Create user journeys', 'Prototype quickly and iterate'],
    },
    curriculum: [
      { title: 'Module 1: UX Foundations', lessons: ['User journeys', 'Information architecture', 'Wireframing'] },
      { title: 'Module 2: UI Systems', lessons: ['Design tokens', 'Typography', 'Components'] },
      { title: 'Module 3: Prototype & Iterate', lessons: ['Prototyping', 'Usability heuristics', 'Iteration cycles'] },
    ],
    instructorDetails: {
      name: 'Charlotte Reed',
      bio: 'UX/UI educator focused on accessibility and product usability.',
      credentials: ['Accessibility-first design', 'Prototype mentoring'],
      rating: 4.7,
    },
    reviews: [
      { name: 'Ravi', role: 'PM', text: 'Excellent for structuring flows and prototypes.' },
      { name: 'Tess', role: 'Designer', text: 'The accessibility guidance was very actionable.' },
      { name: 'Aria', role: 'Founder', text: 'Helped us rethink onboarding and retention.' },
    ],
  },
];

export default COURSES;

