const SERVICES = [
  {
    id: 1,
    name: 'Digital Marketing Services',
    icon: '📈',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    description: 'Increase leads and conversions with measurable digital strategy.',
    deliverables: ['Funnel & campaign planning', 'Performance ad setup', 'Weekly optimization reports'],
    serviceValue: 'Digital Marketing Services',
  },
  {
    id: 2,
    name: 'Project Management Consulting',
    icon: '🛠️',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&auto=format&fit=crop&q=80',
    description: 'Align teams, control scope, and deliver with confidence.',
    deliverables: ['Roadmap & milestone planning', 'Workflow + process setup', 'Risk & stakeholder management'],
    serviceValue: 'Project Management Consulting',
  },
  {
    id: 3,
    name: 'Video Editing & Production',
    icon: '🎬',
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80',
    description: 'Turn raw footage into polished content your audience trusts.',
    deliverables: ['Story-driven editing', 'Color + audio polish', 'Platform-ready exports'],
    serviceValue: 'Video Editing & Production',
  },
  {
    id: 4,
    name: '3D Animation & Motion Graphics',
    icon: '✨',
    image: 'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=600&auto=format&fit=crop&q=80',
    description: 'Add motion and depth that elevate your brand experience.',
    deliverables: ['Motion concept & storyboard', '3D scenes + animations', 'Render + delivery packages'],
    serviceValue: '3D Animation & Motion Graphics',
  },
  {
    id: 5,
    name: 'Data Analytics & Business Intelligence',
    icon: '📊',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    description: 'Make decisions faster with insights built for action.',
    deliverables: ['Dashboard design', 'Data cleaning + modeling', 'KPI reporting and recommendations'],
    serviceValue: 'Data Analytics & Business Intelligence',
  },
  {
    id: 6,
    name: 'Graphic Design & Branding',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=600&auto=format&fit=crop&q=80',
    description: 'Design brand assets that look premium and stay consistent.',
    deliverables: ['Logo & brand kit support', 'Marketing creatives', 'Design system templates'],
    serviceValue: 'Graphic Design & Branding',
  },
  {
    id: 7,
    name: 'Web Development & Maintenance',
    icon: '🌐',
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&auto=format&fit=crop&q=80',
    description: 'Build reliable websites and maintain them end-to-end.',
    deliverables: ['Responsive website development', 'Performance & security checks', 'Ongoing maintenance plan'],
    serviceValue: 'Web Development & Maintenance',
  },
  {
    id: 8,
    name: 'UI/UX Design & Prototyping',
    icon: '🧭',
    image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&auto=format&fit=crop&q=80',
    description: 'Prototype flows and design interfaces that convert.',
    deliverables: ['User flows & wireframes', 'UI components & prototypes', 'Accessibility-first design'],
    serviceValue: 'UI/UX Design & Prototyping',
  },
];

export default SERVICES;

